config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create', as: :new_user
  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create', as: :sessions
  delete 'logout' => 'session#destroy', as: :logout

  get 'import' => 'import#index', as: :import_index
  post 'import' => 'import#import', as: :import
  post 'import/upload' => 'import#upload', as: :import_upload
  get 'stats/last' => 'stats#last', as: :stats_last
  get 'compare' => 'stats#compare', as: :stats_compare

  resources :stats, execpt: [:new, :create]

  resource :user, only: [:edit, :update]
  resources :users, exept: [:edit, :update, :new, :create]

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_filter :require_login

  def index
    @stats = current_user.agent_stats.order(import_date: :desc)
  end

  def show
    @stats = current_user.agent_stats.find(params[:id])
  end

  def last
    stats = AgentStat.last_two(current_user)
    stats_diff(stats)
  end

  def compare
    stats = []
    if params.has_key?('second')
      stats.push current_user.agent_stats.find(params[:second])
    end
    if params.has_key?('first')
      stats.push current_user.agent_stats.find(params[:first])
    end
    stats_diff(stats)

    @options = current_user.agent_stats.reverse
  end

  def edit
    @stats = current_user.agent_stats.find(params[:id])
  end

  def update
    @stats = current_user.agent_stats.find(params[:id])

    respond_to do |format|
      if @stats.update(stats_params)
        format.html { redirect_to stats_path(@stats), notice: 'Agent Stats were successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stats.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stats = current_user.agent_stats.find(params[:id])
    @stats.delete
    respond_to do |format|
      format.html { redirect_to stats_url }
      format.json { head :no_content }
    end
  end

  private
    def stats_diff(stats)
      if stats.any?
        e1 = stats[0]

        @ap = e1.ap.to_i
        @ap_change = 0
        @ap_change_perc = 0.0

        @level = e1.level.to_i
        @level_change = 0
        @level_change_perc = 0.0

        @entries = Hash.new({})

        e1.agent_stats_entries.each do |entry|
          key = entry.name.to_s
          @entries[key] = {value: entry.value.to_i, change: 0, change_perc: 0.0, unit: entry.unit}
        end

        if stats.many?
          @ap_change = @ap - stats[1].ap.to_i
          @ap_change_perc = ((@ap_change.to_f / stats[1].ap.to_f) * 100).to_f
          @level_change= @level - stats[1].level
          @ap_change_perc_perc = ((@level_change.to_f / stats[1].level.to_f) * 100).to_f

          stats[1].agent_stats_entries.each do |entry|
            key = entry.name.to_s
            @entries[key][:change] = @entries[key][:value] - entry.value.to_i
            @entries[key][:change_perc] = ((@entries[key][:change].to_f / entry.value.to_f) * 100).to_f
          end
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stats_params
      params.require(:agent_stat).permit(:name, :level, :ap, addresses_attributes: [:id, :name, :value])
    end
end

app/helpers/stats_helper.rb
module StatsHelper
  KEYWORDS = {
      discovery_0: 'Unique Portals Visited',
      discovery_1: 'Portals Discovered',
      discovery_2: 'XM Collected',

      building_0:  'Hacks',
      building_1:  'Resonators Deployed',
      building_2:  'Links Created',
      building_3:  'Control Fields Created',
      building_4:  'Mind Units Captured',
      building_5:  'Longest Link Ever Created',
      building_6:  'Largest Control Field',
      building_7:  'XM Recharged',
      building_8:  'Portals Captured',
      building_9:  'Unique Portals Captured',

      combat_0:    'Resonators Destroyed',
      combat_1:    'Portals Neutralized',
      combat_2:    'Enemy Links Destroyed',
      combat_3:    'Enemy Control Fields Destroyed',

      health_0:    'Distance Walked',

      defense_0:   'Max Time Portal Held',
      defense_1:   'Max Time Link Maintained',
      defense_2:   'Max Link Length x Days',
      defense_3:   'Max Time Field Held',
      defense_4:   'Largest Field MUs x Days',
  }

  def format_number_color(n, unit = '')
    number = number_with_delimiter(n)

    if n > 0
      return "<span class=\"number-pos\">#{number} #{unit}</span>"
    end

    "<span class=\"number-neg\">#{number} #{unit}</span>"
  end

  def format_percent(n)
    number = number_to_percentage(n)

    if n > 0
      return "<span class=\"number-pos\">#{number}</span>"
    end

    "<span class=\"number-neg\">#{number}</span>"
  end
end

app/views/stats/_table.html.haml
%table
  %tbody
    %tr
      %td Level
      %td= number_with_delimiter(@level)
      %td!= format_number_color(@level_change)
      %td!= format_percent(@level_change_perc)
    %tr
      %td AP
      %td= number_with_delimiter(@ap)
      %td!= format_number_color(@ap_change)
      %td!= format_percent(@ap_change_perc)
    - StatsHelper::KEYWORDS.each do |key, name|
      - entry = @entries[key.to_s]
      %tr
        %td= name
        %td= number_with_delimiter(entry[:value]) + ' ' + entry[:unit]
        %td!= format_number_color(entry[:change], entry[:unit])
        %td!= format_percent(entry[:change_perc])

app/views/stats/compare.html.haml
.row
  .small-12.small-centered.columns
    %h3= t('text.stats.compare')

  .panel
    = form_tag :stats_compare, method: :get do
      .row
        .small-4.medium-5.columns= select_tag :first, options_from_collection_for_select(@options, 'id', 'name', params[:first])
        .small-4.medium-2.columns compare with
        .small-4.medium-5.columns= select_tag :second, options_from_collection_for_select(@options, 'id', 'name', params[:second])
      .row
        .small-12.medium-12.columns.small-centered= submit_tag t('buttons.compare'), class: 'button'
  - if @entries
    = render template: 'stats/_table'

app/views/stats/edit.html.haml
.row
  .small-12.small-centered.columns
    %h3= t('text.stats.edit')

  .panel
    = form_for @stats, :url => :stat do |f|
      .row
        .small-12.columns
          = f.text_field :name
      .row
        .small-12.columns
          = f.text_field :import_date
      .row
        .small-12.columns
          = f.text_field :level
      .row
        .small-12.columns
          = f.text_field :ap
      = f.fields_for :agent_stats_entries do |entry|
        .row
          .small-6.columns
            = entry.text_field :display_name, disabled: true
          .small-6.columns
            = entry.text_field :value
      .row
        .small-12.columns
          = f.submit

app/views/stats/index.html.haml
.row
  .small-12.small-centered.columns
    %h3= t('text.stats.index')

  .panel
    %table
      %thead
        %tr
          %th= t('activerecord.attributes.agent_stat.name')
          %th= t('activerecord.attributes.agent_stat.import_date')
          %th= t('activerecord.attributes.agent_stat.level')
          %th= t('activerecord.attributes.agent_stat.ap')
          %th ...
      %tbody
        - @stats.each do |entry|
          %tr
            %td= link_to entry.name, stat_path(entry)
            %td= entry.import_date.to_s(:db)
            %td= entry.level
            %td= number_with_delimiter(entry.ap)
            %td
              = link_to 'edit', edit_stat_path(entry), class: ['button', 'tiny']
              = link_to 'delete',  stat_path(entry), method: :delete, class: ['button', 'tiny', 'alert'], data: { confirm: "Are you sure?" }

app/views/stats/last.html.haml
.row
  .small-12.small-centered.columns
    %h3= t('text.stats.index')

  .panel
    = render template: 'stats/_table'

app/views/stats/show.html.haml
.row
  .small-12.small-centered.columns
    %h3= t('text.stats.show')

  .panel
    .row
      .small-8.columns
        %table
          %tbody
            %tr
              %td Level
              %td= number_with_delimiter(@stats.level)
            %tr
              %td AP
              %td= number_with_delimiter(@stats.ap)
            - @stats.agent_stats_entries.each do |entry|
              %tr
                %td= StatsHelper::KEYWORDS[entry.name.to_sym]
                %td= number_with_delimiter(entry[:value]) + ' ' + entry.unit
      .small-4.columns
        - @stats.agent_stats_uploads.each do |upload|
          .upload= image_tag(upload.screenshot, class: 'thumb')